name: test-and-build

on:
  push: {}

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:2026.31.2@sha256:3ef7f24932aa2d18440c71e39ad714bfe06a7319f2753d5d6138afbe0a62f08b
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint and test code
        run: |
          go test -v ./...

      - name: Build Locally
        run: go build .

      - name: Execute Trivy scan
        run: make trivy
