name: test-and-build

on:
  push: {}

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:ca055dbb97329e9cee06afe92704f534e310e7e3b5c2f4f3618799355172f52c
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Lint and test code
        run: |
          go test -v ./...

      - name: Build Locally
        run: go build .

      - name: Execute Trivy scan
        run: make trivy
