name: test-and-build

on:
  push: {}

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:7a160b28fbf31ed8c776b52b44313ee1ef21da85845a359e1dff30c7a8340fea
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint and test code
        run: |
          go test -v ./...

      - name: Build Locally
        run: go build .

      - name: Execute Trivy scan
        run: make trivy
